telegram:
    whoami: <%= username %>
    <%= username %>:
        name: <%= name %>
        token: <%= token %>
    authorization:
        enabled: <%= auth_enabled %>
        max_chats: <%= auth_max_chats %>
        auth_timeout: <%= auth_timeout %>

